# This file was generated by GoReleaser. DO NOT EDIT.
class Ax < Formula
  desc "jwt decoder."
  homepage "https://github.com/itooww/ax/"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/itooww/ax/releases/download/v0.0.5/ax_darwin_x86_64.tar.gz"
    sha256 "b46938dea4ddc37432e56c033677f00ae0878ceba23fcb00cf093ee5f9ed4dd7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/itooww/ax/releases/download/v0.0.5/ax_linux_x86_64.tar.gz"
      sha256 "557c5c71362f31fed5bd3d798e607942c240da53af4562cc817953afd931a2c8"
    end
  end

  def install
    bin.install "ax"
  end
end
